//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLab4
{
    using System;
    using System.Collections.Generic;
    
    public partial class catsitter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catsitter()
        {
            this.cats = new HashSet<cats>();
        }
    
        public int ID_catsitter { get; set; }
        public string firstname { get; set; }
        public string surname { get; set; }
        public string midlename { get; set; }
        public Nullable<int> workexperience { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cats> cats { private get; set; }
    }
}
